#!/bin/bash

# 修复所有文章的front matter格式
# 将旧格式转换为Hugo Blox兼容的新格式

echo "开始修复文章front matter格式..."

# 定义需要修复的文件列表
files=(
    "content/blog/linux/Linux 常用脚本.md"
    "content/blog/notes/后端工程目录结构设计.md"
    "content/blog/golang/Go_perf.md"
    "content/blog/golang/design_parttern.md"
    "content/blog/linux/linux init.md"
    "content/blog/golang/OnionModel.md"
    "content/blog/golang/DEMO.md"
    "content/blog/python/pip升级问题.md"
    "content/blog/golang/The Go Programming Language（8）- channel.md"
    "content/blog/golang/Nacos-sdk-go v2.0.0-Beta.1.md"
    "content/blog/python/01丨Python 基础.md"
    "content/blog/golang/singleton.md"
    "content/blog/python/Python 基础.md"
    "content/blog/python/Django.md"
    "content/blog/golang/golang-demo.md"
    "content/blog/golang/The Go Programming Language（9）.md"
    "content/blog/golang/Go Bug 合集.md"
    "content/blog/rust/01丨Rust 基础.md"
    "content/blog/golang/The Go Programming Language（0-5）.md"
    "content/blog/golang/GO专家编程.md"
    "content/blog/golang/The Go Programming Language（6-7）.md"
    "content/blog/cloud-native/Minikube Install.md"
    "content/blog/golang/The Go Programming Language（8）- goroutine.md"
    "content/blog/golang/The Go Programming Language（10-13）.md"
    "content/blog/cloud-native/k8s question.md"
    "content/blog/cloud-native/kubectl 备忘单.md"
    "content/blog/cloud-native/20220102-day1.md"
    "content/blog/cloud-native/01 docker.md"
    "content/blog/cloud-native/01-docker.md"
    "content/blog/cloud-native/20220109-day2.md"
    "content/blog/golang/Golang-100-days.md"
    "content/blog/cloud-native/02 Kubernetes.md"
    "content/blog/cloud-native/Docker Install.md"
    "content/blog/golang/Go Web.md"
    "content/blog/cloud-native/Kubernetes Install.md"
    "content/blog/cloud-native/deploy.md"
)

# 为每个文件分配合适的图片
declare -A file_images
file_images["content/blog/linux/Linux 常用脚本.md"]="linux-logo.svg"
file_images["content/blog/notes/后端工程目录结构设计.md"]="blog-default.svg"
file_images["content/blog/golang/Go_perf.md"]="golang-logo.svg"
file_images["content/blog/golang/design_parttern.md"]="golang-logo.svg"
file_images["content/blog/linux/linux init.md"]="linux-logo.svg"
file_images["content/blog/golang/OnionModel.md"]="golang-logo.svg"
file_images["content/blog/golang/DEMO.md"]="golang-logo.svg"
file_images["content/blog/python/pip升级问题.md"]="python-logo.svg"
file_images["content/blog/golang/The Go Programming Language（8）- channel.md"]="golang-logo.svg"
file_images["content/blog/golang/Nacos-sdk-go v2.0.0-Beta.1.md"]="golang-logo.svg"
file_images["content/blog/python/01丨Python 基础.md"]="python-logo.svg"
file_images["content/blog/golang/singleton.md"]="golang-logo.svg"
file_images["content/blog/python/Python 基础.md"]="python-logo.svg"
file_images["content/blog/python/Django.md"]="python-logo.svg"
file_images["content/blog/golang/golang-demo.md"]="golang-logo.svg"
file_images["content/blog/golang/The Go Programming Language（9）.md"]="golang-logo.svg"
file_images["content/blog/golang/Go Bug 合集.md"]="golang-logo.svg"
file_images["content/blog/rust/01丨Rust 基础.md"]="rust-logo.svg"
file_images["content/blog/golang/The Go Programming Language（0-5）.md"]="golang-logo.svg"
file_images["content/blog/golang/GO专家编程.md"]="golang-logo.svg"
file_images["content/blog/golang/The Go Programming Language（6-7）.md"]="golang-logo.svg"
file_images["content/blog/cloud-native/Minikube Install.md"]="kubernetes-logo.svg"
file_images["content/blog/golang/The Go Programming Language（8）- goroutine.md"]="golang-logo.svg"
file_images["content/blog/golang/The Go Programming Language（10-13）.md"]="golang-logo.svg"
file_images["content/blog/cloud-native/k8s question.md"]="kubernetes-logo.svg"
file_images["content/blog/cloud-native/kubectl 备忘单.md"]="kubernetes-logo.svg"
file_images["content/blog/cloud-native/20220102-day1.md"]="kubernetes-logo.svg"
file_images["content/blog/cloud-native/01 docker.md"]="docker-logo.svg"
file_images["content/blog/cloud-native/01-docker.md"]="docker-logo.svg"
file_images["content/blog/cloud-native/20220109-day2.md"]="kubernetes-logo.svg"
file_images["content/blog/golang/Golang-100-days.md"]="golang-logo.svg"
file_images["content/blog/cloud-native/02 Kubernetes.md"]="kubernetes-logo.svg"
file_images["content/blog/cloud-native/Docker Install.md"]="docker-logo.svg"
file_images["content/blog/golang/Go Web.md"]="golang-logo.svg"
file_images["content/blog/cloud-native/Kubernetes Install.md"]="kubernetes-logo.svg"
file_images["content/blog/cloud-native/deploy.md"]="kubernetes-logo.svg"

echo "脚本创建完成，需要手动执行修复操作"